name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build macOS .app
      run: |
        pyinstaller --windowed --onefile your_script.py

    - name: Upload built app
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: dist/
