name: Build macOS App

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build macOS .app bundle
      run: |
        pyinstaller --windowed createPNG.py

    - name: Zip the .app bundle
      run: |
        cd dist
        zip -r your_script.app.zip your_script.app

    - name: Upload zipped .app
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: dist/your_script.app.zip
